import { Category, Product } from '../dummy-types/product';

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Arroz Integral',
    userId: 'user-1',
    unit: 'KILOS',
    category: Category.ABARROTES,
    estimatedStock: 2.5,
    dailyConsumption: 0.1,
    criticalStock: false,
  },
  {
    id: '2',
    name: 'Leche Entera',
    userId: 'user-1',
    unit: 'LITERS',
    category: Category.LACTEOS,
    estimatedStock: 0.5,
    dailyConsumption: 0.2,
    criticalStock: true,
  },
  {
    id: '3',
    name: 'Manzanas',
    userId: 'user-1',
    unit: 'UNITS',
    category: Category.FRUTAS,
    estimatedStock: 3,
    dailyConsumption: 1,
    criticalStock: true,
  },
  {
    id: '4',
    name: 'Detergente Líquido',
    userId: 'user-1',
    unit: 'MILLILITERS',
    category: Category.LIMPIEZA,
    estimatedStock: 600,
    dailyConsumption: 50,
    criticalStock: false,
  },
  {
    id: '5',
    name: 'Jamón de Pavo',
    userId: 'user-1',
    unit: 'GRAMS',
    category: Category.CARNE,
    estimatedStock: 120,
    dailyConsumption: 30,
    criticalStock: false,
  },
];
